version: 1.0.{build}
image: Visual Studio 2015
build_script:
- cmd: PowerShell -Version 2.0 .\build.ps1
test: off

artifacts:
  - path: bin
    name: test
    type: zip

deploy:
  provider: S3
  access_key_id: 
  secret_access_key: 
  bucket: rockport-saml-test-sp
  region: us-east-2
  unzip: false
  set_public: true
  folder: code
  artifact: test